name: dji_smart_health
description: Aplikasi kesehatan pintar untuk memantau aktivitas dan kesehatan Anda.
version: 1.0.0+1
environment:
sdk: ">=2.12.0 <3.0.0"
dependencies:
flutter:
sdk: flutter
fluttertoast: ^8.0.9
http: ^0.13.3
flutter_secure_storage: ^5.0.2
flutter_spinkit: ^5.0.0
charts_flutter: ^0.10.0
filament: ^1.0.0
